#############################################################################
# Makefile for building: sniffer-udea
# Generated by qmake (1.07a) (Qt 3.3.8) on: Tue Mar 31 11:02:21 2009
# Project:  sniffer-udea.pro
# Template: app
# Command: $(QMAKE) -o Makefile sniffer-udea.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -march=i686 -mtune=generic -O2 -pipe  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -march=i686 -mtune=generic -O2 -pipe  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/opt/qt/mkspecs/default -I. -I. -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = sniffer.h \
		sniffThread.h \
		uiFilter.ui.h
SOURCES = main.cpp \
		sniffer.cpp \
		sniffThread.cpp
OBJECTS = main.o \
		sniffer.o \
		sniffThread.o \
		uiFilter.o
FORMS = uiFilter.ui
UICDECLS = uiFilter.h
UICIMPLS = uiFilter.cpp
SRCMOC   = moc_uiFilter.cpp
OBJMOC = moc_uiFilter.o
DIST	   = sniffer-udea.pro
QMAKE_TARGET = sniffer-udea
DESTDIR  = 
TARGET   = sniffer-udea

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: sniffer-udea.pro  /opt/qt/mkspecs/default/qmake.conf /opt/qt/lib/libqt-mt.prl
	$(QMAKE) -o Makefile sniffer-udea.pro
qmake: 
	@$(QMAKE) -o Makefile sniffer-udea.pro

dist: 
	@mkdir -p .tmp/sniffer-udea && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/sniffer-udea/ && $(COPY_FILE) --parents uiFilter.ui.h .tmp/sniffer-udea/ && ( cd `dirname .tmp/sniffer-udea` && $(TAR) sniffer-udea.tar sniffer-udea && $(GZIP) sniffer-udea.tar ) && $(MOVE) `dirname .tmp/sniffer-udea`/sniffer-udea.tar.gz . && $(DEL_FILE) -r .tmp/sniffer-udea

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

main.o: main.cpp uiFilter.h

sniffer.o: sniffer.cpp sniffer.h

sniffThread.o: sniffThread.cpp sniffThread.h \
		sniffer.h

uiFilter.h: uiFilter.ui 
	$(UIC) uiFilter.ui -o uiFilter.h

uiFilter.cpp: uiFilter.h uiFilter.ui uiFilter.ui.h 
	$(UIC) uiFilter.ui -i uiFilter.h -o uiFilter.cpp

uiFilter.o: uiFilter.cpp uiFilter.ui.h \
		uiFilter.h

moc_uiFilter.o: moc_uiFilter.cpp  uiFilter.h 

moc_uiFilter.cpp: $(MOC) uiFilter.h
	$(MOC) uiFilter.h -o moc_uiFilter.cpp

####### Install

install:  

uninstall:  

