######################################################################
# Automatically generated by qmake (1.07a) Thu Apr 2 16:48:19 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += sniffer.h sniffThread.h uiFilter.ui.h
INTERFACES += uiFilter.ui
SOURCES += main.cpp sniffer.cpp sniffThread.cpp
