######################################################################
# Automatically generated by qmake (1.07a) Tue Mar 31 11:02:17 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += sniffer.h sniffThread.h uiFilter.ui.h
INTERFACES += uiFilter.ui
SOURCES += main.cpp sniffer.cpp sniffThread.cpp
